#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
wm-restack = i3

bspc monitor DisplayPort-0 -d I III V VII IX 
bspc monitor HDMI-A-0 -d II IV VI VIII X

bspc config border_width        3
bspc config window_gap          20
spc config bottom_padding       3
bspc config split_ratio         -1
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#665c54"
bspc config presel_feedback_color   "#7c6f64"

rspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a "Steam - News" state=floating
